# Generated by Django 6.0.5 on 2026-05-08 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to application logo', max_length=500)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Domain / URL')),
                ('local_ip', models.CharField(blank=True, max_length=100, verbose_name='Local IP')),
                ('port', models.CharField(blank=True, max_length=10)),
                ('environment', models.CharField(choices=[('DEV', 'Development'), ('BETA', 'Beta/Staging'), ('PROD', 'Production')], default='DEV', max_length=10)),
                ('framework', models.CharField(blank=True, help_text='Backend/Framework (e.g., Django, Node.js)', max_length=100)),
                ('database', models.CharField(blank=True, max_length=100)),
                ('repository', models.URLField(blank=True, max_length=500, verbose_name='Git Repository')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('deployment_notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='categories.category')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='servers.server')),
            ],
        ),
        migrations.CreateModel(
            name='AppAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Nomor WhatsApp')),
                ('access_notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.application')),
            ],
            options={
                'verbose_name_plural': 'Update Histories',
                'ordering': ['-date'],
            },
        ),
    ]
