# Generated by Django 6.0.5 on 2026-05-12 09:45

import django.db.models.deletion
from django.db import migrations, models


def migrate_application_environments(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    ApplicationEnvironment = apps.get_model('applications', 'ApplicationEnvironment')

    for application in Application.objects.all():
        ApplicationEnvironment.objects.get_or_create(
            application_id=application.id,
            environment=application.environment,
            defaults={
                'server_id': application.server_id,
                'url': application.url,
                'local_ip': application.local_ip,
                'port': application.port,
                'is_active': application.is_active,
                'deployment_notes': application.deployment_notes,
            },
        )


def restore_application_environments(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    ApplicationEnvironment = apps.get_model('applications', 'ApplicationEnvironment')

    env_order = {'DEV': 1, 'BETA': 2, 'PROD': 3}
    for application in Application.objects.all():
        environments = ApplicationEnvironment.objects.filter(application_id=application.id)
        highest_environment = max(environments, key=lambda item: env_order.get(item.environment, 0), default=None)
        if not highest_environment:
            continue

        application.environment = highest_environment.environment
        application.server_id = highest_environment.server_id
        application.url = highest_environment.url
        application.local_ip = highest_environment.local_ip
        application.port = highest_environment.port
        application.is_active = highest_environment.is_active
        application.save(update_fields=['environment', 'server', 'url', 'local_ip', 'port', 'is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('DEV', 'Development'), ('BETA', 'Beta/Staging'), ('PROD', 'Production')], max_length=10)),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Domain / URL')),
                ('local_ip', models.CharField(blank=True, max_length=100, verbose_name='Local IP')),
                ('port', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('deployment_notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='applications.application')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_environments', to='servers.server')),
            ],
            options={
                'ordering': ['application', 'environment'],
                'constraints': [models.UniqueConstraint(fields=('application', 'environment'), name='unique_application_environment')],
            },
        ),
        migrations.RunPython(migrate_application_environments, restore_application_environments),
        migrations.RemoveField(
            model_name='application',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='application',
            name='local_ip',
        ),
        migrations.RemoveField(
            model_name='application',
            name='port',
        ),
        migrations.RemoveField(
            model_name='application',
            name='server',
        ),
        migrations.RemoveField(
            model_name='application',
            name='url',
        ),
    ]
