# Generated by Django 6.0.5 on 2026-05-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host_ip', models.CharField(max_length=100, verbose_name='Host/IP Server')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Sistem Operasi')),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('specs', models.TextField(blank=True, verbose_name='Spesifikasi Server')),
                ('deployment_notes', models.TextField(blank=True)),
            ],
        ),
    ]
