# Generated by Django 6.0.5 on 2026-05-15 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAgentMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_url', models.URLField(max_length=500)),
                ('agent_auth_key', models.CharField(max_length=255)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_monitor', to='servers.server')),
            ],
        ),
    ]
