# Generated by Django 6.0.5 on 2026-05-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color or Tailwind color class', max_length=20)),
                ('icon', models.CharField(default='fa-cube', help_text='FontAwesome icon class (e.g., fa-cube)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
